# Pokemon Abilities Data - Complete
# Extracted from habilitats.txt

# Format: (id, name, description, overworld_effect)
ABILITIES = [
    (1, 'Adaptibility', 'If this Pokémon uses an attack that has the same type as it, then the move''s power is increased', None),
    (2, 'Aftermath', 'If this Pokémon was fainted by a Physical Attack, the opponent receives damage', None),
    (3, 'Air Lock', 'All weather effects are nulled while this Pokémon is on the field', None),
    (4, 'Anger Point', 'This Pokémon''s attack rises when hit with a Critical Hit', None),
    (5, 'Anticipation', 'Tells you if your foe has a Super Effective Attack', None),
    (6, 'Arena Trap', 'The opponent can neither run or switch. Flying type Pokémon and those with the Levitate Ability are unaffected', 'Chance of encountering wild Pokémon increased to 200%'),
    (7, 'Bad Dreams', 'If the opponent is asleep, it loses health every turn', None),
    (8, 'Battle Armor', 'Opponent''s moves cannot Critical Hit', None),
    (9, 'Blaze', 'When HP is below 1/3rd, Fire power increases to 1.5x', None),
    (10, 'Cacophony', 'Unaffected by sound moves', None),
    (11, 'Chlorophyll', 'Speed doubles in sunshine', None),
    (12, 'Clear Body', 'Prevents stat reduction from opponent', None),
    (13, 'Cloud Nine', 'Negates all weather effects', None),
    (14, 'Color Change', 'Changes type to match last damaging move received', None),
    (15, 'Compoundeyes', 'Raises accuracy by 30%', 'Increases chance of wild Pokémon holding items'),
    (16, 'Cute Charm', '30% chance to attract opponent on contact', 'Increases opposite gender encounters to 66.6%'),
    (17, 'Damp', 'Prevents Explosion and Selfdestruct', None),
    (18, 'Download', 'Raises Attack or Special Attack based on foe''s weaker defense', None),
    (19, 'Drizzle', 'Summons rain when entering battle', None),
    (20, 'Drought', 'Summons sunshine when entering battle', None),
    (21, 'Dry Skin', 'HP decreases in sun, increases in rain', None),
    (22, 'Early Bird', 'Sleep duration is halved', None),
    (23, 'Effect Spore', '10% chance to inflict Paralysis, Poison, or Sleep on contact', None),
    (24, 'Filter', 'Super effective attacks deal half damage', None),
    (25, 'Flame Body', '30% chance to burn opponent on contact', 'Eggs hatch in half the time'),
    (26, 'Flash Fire', 'Immune to Fire moves, Fire power increases 1.5x when hit by Fire', None),
    (27, 'Flower Gift', 'Form changes in sunshine, stats raised', None),
    (28, 'Forecast', 'Type and form change with weather', None),
    (29, 'Forewarn', 'Reveals opponent''s strongest move', None),
    (30, 'Frisk', 'Reveals opponent''s held item', None),
    (31, 'Gluttony', 'Uses held berries earlier', None),
    (32, 'Guts', 'Attack increases 1.5x when affected by status', None),
    (33, 'Heat Proof', 'Fire attacks deal reduced damage', None),
    (34, 'Honey Gather', 'Collects honey after battle', None),
    (35, 'Huge Power', 'Attack doubled', None),
    (36, 'Hustle', 'Attack increased 1.5x but accuracy decreased to 80%', 'Lower level wild encounters'),
    (37, 'Hydration', 'All status conditions cured in rain', None),
    (38, 'Hyper Cutter', 'Prevents Attack reduction', 'Cut affects larger grass area'),
    (39, 'Ice Body', 'HP recovers during hail', None),
    (40, 'Illuminate', 'Encounter rate doubled', 'Wild encounters increased to 200%'),
    (41, 'Immunity', 'Cannot be poisoned', None),
    (42, 'Inner Focus', 'Cannot flinch', None),
    (43, 'Insomnia', 'Cannot fall asleep', None),
    (44, 'Intimidate', 'Lowers opponent''s Attack one stage on entry', 'Lower level wild encounters'),
    (45, 'Iron Fist', 'Punching moves have increased power', None),
    (46, 'Keen Eye', 'Prevents accuracy reduction', 'Lower level wild encounters'),
    (47, 'Klutz', 'Cannot use held items', None),
    (48, 'Leaf Guard', 'Status conditions healed in sunshine', None),
    (49, 'Levitate', 'Immune to Ground-type moves', None),
    (50, 'Lightning Rod', 'Draws Electric-type moves', 'Electric-type encounters increased'),
    (51, 'Limber', 'Cannot be paralyzed', None),
    (52, 'Liquid Ooze', 'Damages opponent when they absorb HP', None),
    (53, 'Magic Guard', 'Only damaged by direct attacks', None),
    (54, 'Magma Armor', 'Cannot be frozen', 'Eggs hatch in half the time'),
    (55, 'Magnet Pull', 'Traps Steel-type Pokémon', 'Steel-type encounters increased to 150%'),
    (56, 'Marvel Scale', 'Defense increases 1.5x when affected by status', None),
    (57, 'Minus', 'Special Attack increases 1.5x when paired with Plus', None),
    (58, 'Mold Breaker', 'Ignores opponent''s ability', None),
    (59, 'Motor Drive', 'Speed increases when hit by Electric-type move', None),
    (60, 'MultiType', 'Type changes based on held Plate', None),
    (61, 'Natural Cure', 'Status healed when withdrawn', None),
    (62, 'No Guard', 'All moves have 100% accuracy', None),
    (63, 'Normalize', 'All moves become Normal-type', None),
    (64, 'Oblivious', 'Cannot be attracted', None),
    (65, 'Overgrow', 'When HP below 1/3rd, Grass power increases 1.5x', None),
    (66, 'Own Tempo', 'Cannot be confused', None),
    (67, 'PickUp', '10% chance to find item after battle', None),
    (68, 'Plus', 'Special Attack increases 1.5x when paired with Minus', None),
    (69, 'Poison Heal', 'HP increases when poisoned', None),
    (70, 'Poison Point', '30% chance to poison opponent on contact', None),
    (71, 'Pressure', 'Opponent''s PP depletes 2 per move instead of 1', 'Fewer high-level encounters'),
    (72, 'Pure Power', 'Attack doubled', None),
    (73, 'Quick Feet', 'Speed increases when affected by status', None),
    (74, 'Reckless', 'Recoil moves have increased power', None),
    (75, 'Rivalry', 'Attack increases against same gender', None),
    (76, 'Rain Dish', 'Recovers 1/16 max HP in rain', None),
    (77, 'Rock Head', 'No recoil damage', None),
    (78, 'Rough Skin', 'Damages opponent 1/16 HP on contact', None),
    (79, 'Run Away', 'Can always flee from wild battles', None),
    (80, 'Sand Stream', 'Summons sandstorm when entering battle', None),
    (81, 'Sand Veil', 'Evasion increases in sandstorm', 'Fewer encounters in sandstorm'),
    (82, 'Scrappy', 'Can hit Ghost-types with Normal and Fighting moves', None),
    (83, 'Serene Grace', 'Move secondary effect chance doubled', None),
    (84, 'Shadow Tag', 'Prevents opponent from fleeing or switching', None),
    (85, 'Shed Skin', '33% chance to heal status each turn', None),
    (86, 'Shell Armor', 'Cannot be critically hit', None),
    (87, 'Shield Dust', 'Immune to move secondary effects', None),
    (88, 'Simple', 'Stat changes are doubled', None),
    (89, 'Skill Link', 'Multi-hit moves always hit maximum times', None),
    (90, 'Slow Start', 'Attack and Speed halved for 5 turns', None),
    (91, 'Sniper', 'Critical hits deal increased damage', None),
    (92, 'Snow Cloak', 'Evasion increases in hail', None),
    (93, 'Snow Warning', 'Summons hail when entering battle', None),
    (94, 'Solar Power', 'Special Attack increases in sun but HP decreases', None),
    (95, 'Solid Rock', 'Super effective attacks deal reduced damage', None),
    (96, 'Soundproof', 'Immune to sound-based moves', None),
    (97, 'Speed Boost', 'Speed increases one stage each turn', None),
    (98, 'Static', '30% chance to paralyze opponent on contact', 'Electric-type encounters increased to 150%'),
    (99, 'Stall', 'Always moves last', None),
    (100, 'Steadfast', 'Speed increases when flinched', None),
    (101, 'Stench', 'May cause opponent to flinch', 'Wild encounters decreased to 50%'),
    (102, 'Sticky Hold', 'Item cannot be stolen', 'Easier to catch fish'),
    (103, 'Storm Drain', 'Draws Water-type moves', None),
    (104, 'Sturdy', 'Immune to OHKO moves', None),
    (105, 'Suction Cups', 'Cannot be forced to switch', 'Easier to catch fish'),
    (106, 'Super Luck', 'Higher critical hit ratio', None),
    (107, 'Swarm', 'When HP below 1/3rd, Bug power increases 1.5x', 'Hear wild Pokémon more often'),
    (108, 'Swift Swim', 'Speed doubles in rain', None),
    (109, 'Synchronize', 'Passes status conditions to opponent', '50% chance to encounter same nature'),
    (110, 'Tangled Feet', 'Evasion increases when confused', None),
    (111, 'Technician', 'Weak moves have increased power', None),
    (112, 'Thick Fat', 'Fire and Ice moves deal 50% damage', None),
    (113, 'Tinted Lens', 'Not very effective moves deal normal damage', None),
    (114, 'Torrent', 'When HP below 1/3rd, Water power increases 1.5x', None),
    (115, 'Trace', 'Copies opponent''s ability', None),
    (116, 'Truant', 'Can only attack every other turn', None),
    (117, 'Unaware', 'Ignores opponent''s stat changes', None),
    (118, 'Unburden', 'Speed doubles when item is consumed', None),
    (119, 'Vital Spirit', 'Cannot fall asleep', 'Fewer high-level encounters'),
    (120, 'Volt Absorb', 'Heals 1/4 max HP when hit by Electric moves', None),
    (121, 'Water Absorb', 'Heals 1/4 max HP when hit by Water moves', None),
    (122, 'Water Veil', 'Cannot be burned', None),
    (123, 'White Smoke', 'Prevents stat reduction', 'Wild encounters decreased to 50%'),
    (124, 'Wonder Guard', 'Only damaged by super effective moves', None),
]

# Note: Pokemon-Ability mappings should be added after manual verification
# This would require matching Pokemon names from the text file to database IDs
