# Pokemon Abilities Data
# Auto-generated from PokeAPI
# Format: (id, name, description, overworld_effect)

ABILITIES = [
    (1, 'Stench', 'Has a 10% chance of making target Pokémon flinch with each hit.', None),
    (2, 'Drizzle', 'Summons rain that lasts indefinitely upon entering battle.', None),
    (3, 'Speed Boost', 'Raises Speed one stage after each turn.', None),
    (4, 'Battle Armor', 'Protects against critical hits.', None),
    (5, 'Sturdy', 'Prevents being KOed from full HP, leaving 1 HP instead.  Protects against the one-hit KO moves regardless of HP.', None),
    (6, 'Damp', 'Prevents self destruct, explosion, and aftermath from working while the Pokémon is in battle.', None),
    (7, 'Limber', 'Prevents paralysis.', None),
    (8, 'Sand Veil', 'Increases evasion to 1.25× during a sandstorm.  Protects against sandstorm damage.', None),
    (9, 'Static', 'Has a 30% chance of paralyzing attacking Pokémon on contact.', None),
    (10, 'Volt Absorb', 'Absorbs electric moves, healing for 1/4 max HP.', None),
    (11, 'Water Absorb', 'Absorbs water moves, healing for 1/4 max HP.', None),
    (12, 'Oblivious', 'Prevents infatuation and protects against captivate.', None),
    (13, 'Cloud Nine', 'Negates all effects of weather, but does not prevent the weather itself.', None),
    (14, 'Compound Eyes', 'Increases moves\' accuracy to 1.3×.', None),
    (15, 'Insomnia', 'Prevents sleep.', None),
    (16, 'Color Change', 'Changes type to match when hit by a damaging move.', None),
    (17, 'Immunity', 'Prevents poison.', None),
    (18, 'Flash Fire', 'Protects against fire moves.  Once one has been blocked, the Pokémon\'s own Fire moves inflict 1.5× damage until it leaves battle.', None),
    (19, 'Shield Dust', 'Protects against incoming moves\' extra effects.', None),
    (20, 'Own Tempo', 'Prevents confusion.', None),
    (21, 'Suction Cups', 'Prevents being forced out of battle by other Pokémon\'s moves.', None),
    (22, 'Intimidate', 'Lowers opponents\' Attack one stage upon entering battle.', None),
    (23, 'Shadow Tag', 'Prevents opponents from fleeing or switching out.', None),
    (24, 'Rough Skin', 'Damages attacking Pokémon for 1/8 their max HP on contact.', None),
    (25, 'Wonder Guard', 'Protects against damaging moves that are not super effective.', None),
    (26, 'Levitate', 'Evades ground moves.', None),
    (27, 'Effect Spore', 'Has a 30% chance of inflcting either paralysis, poison, or sleep on attacking Pokémon on contact.', None),
    (28, 'Synchronize', 'Copies burns, paralysis, and poison received onto the Pokémon that inflicted them.', None),
    (29, 'Clear Body', 'Prevents stats from being lowered by other Pokémon.', None),
    (30, 'Natural Cure', 'Cures any major status ailment upon switching out.', None),
    (31, 'Lightning Rod', 'Redirects single-target electric moves to this Pokémon where possible.  Absorbs Electric moves, raising Special Attack one stage.', None),
    (32, 'Serene Grace', 'Doubles the chance of moves\' extra effects occurring.', None),
    (33, 'Swift Swim', 'Doubles Speed during rain.', None),
    (34, 'Chlorophyll', 'Doubles Speed during strong sunlight.', None),
    (35, 'Illuminate', 'Doubles the wild encounter rate.', None),
    (36, 'Trace', 'Copies an opponent\'s ability upon entering battle.', None),
    (37, 'Huge Power', 'Doubles Attack in battle.', None),
    (38, 'Poison Point', 'Has a 30% chance of poisoning attacking Pokémon on contact.', None),
    (39, 'Inner Focus', 'Prevents flinching.', None),
    (40, 'Magma Armor', 'Prevents freezing.', None),
    (41, 'Water Veil', 'Prevents burns.', None),
    (42, 'Magnet Pull', 'Prevents steel opponents from fleeing or switching out.', None),
    (43, 'Soundproof', 'Protects against sound-based moves.', None),
    (44, 'Rain Dish', 'Heals for 1/16 max HP after each turn during rain.', None),
    (45, 'Sand Stream', 'Summons a sandstorm that lasts indefinitely upon entering battle.', None),
    (46, 'Pressure', 'Increases the PP cost of moves targetting the Pokémon by one.', None),
    (47, 'Thick Fat', 'Halves damage from fire and ice moves.', None),
    (48, 'Early Bird', 'Makes sleep pass twice as quickly.', None),
    (49, 'Flame Body', 'Has a 30% chance of burning attacking Pokémon on contact.', None),
    (50, 'Run Away', 'Ensures success fleeing from wild battles.', None),
    (51, 'Keen Eye', 'Prevents accuracy from being lowered.', None),
    (52, 'Hyper Cutter', 'Prevents Attack from being lowered by other Pokémon.', None),
    (53, 'Pickup', 'Picks up other Pokémon\'s used and Flung held items.  May also pick up an item after battle.', None),
    (54, 'Truant', 'Skips every second turn.', None),
    (55, 'Hustle', 'Strengthens physical moves to inflict 1.5× damage, but decreases their accuracy to 0.8×.', None),
    (56, 'Cute Charm', 'Has a 30% chance of infatuating attacking Pokémon on contact.', None),
    (57, 'Plus', 'Increases Special Attack to 1.5× when a friendly Pokémon has plus or minus.', None),
    (58, 'Minus', 'Increases Special Attack to 1.5× when a friendly Pokémon has plus or minus.', None),
    (59, 'Forecast', 'Changes castform\'s type and form to match the weather.', None),
    (60, 'Sticky Hold', 'Prevents a held item from being removed by other Pokémon.', None),
    (61, 'Shed Skin', 'Has a 33% chance of curing any major status ailment after each turn.', None),
    (62, 'Guts', 'Increases Attack to 1.5× with a major status ailment.', None),
    (63, 'Marvel Scale', 'Increases Defense to 1.5× with a major status ailment.', None),
    (64, 'Liquid Ooze', 'Damages opponents using leeching moves for as much as they would heal.', None),
    (65, 'Overgrow', 'Strengthens grass moves to inflict 1.5× damage at 1/3 max HP or less.', None),
    (66, 'Blaze', 'Strengthens fire moves to inflict 1.5× damage at 1/3 max HP or less.', None),
    (67, 'Torrent', 'Strengthens water moves to inflict 1.5× damage at 1/3 max HP or less.', None),
    (68, 'Swarm', 'Strengthens bug moves to inflict 1.5× damage at 1/3 max HP or less.', None),
    (69, 'Rock Head', 'Protects against recoil damage.', None),
    (70, 'Drought', 'Summons strong sunlight that lasts indefinitely upon entering battle.', None),
    (71, 'Arena Trap', 'Prevents opponents from fleeing or switching out.  Eluded by flying-types and Pokémon in the air.', None),
    (72, 'Vital Spirit', 'Prevents sleep.', None),
    (73, 'White Smoke', 'Prevents stats from being lowered by other Pokémon.', None),
    (74, 'Pure Power', 'Doubles Attack in battle.', None),
    (75, 'Shell Armor', 'Protects against critical hits.', None),
    (76, 'Air Lock', 'Negates all effects of weather, but does not prevent the weather itself.', None),
    (77, 'Tangled Feet', 'Doubles evasion when confused.', None),
    (78, 'Motor Drive', 'Absorbs electric moves, raising Speed one stage.', None),
    (79, 'Rivalry', 'Increases damage inflicted to 1.25× against Pokémon of the same gender, but decreases damage to 0.75× against the opposite gender.', None),
    (80, 'Steadfast', 'Raises Speed one stage upon flinching.', None),
    (81, 'Snow Cloak', 'Increases evasion to 1.25× during hail.  Protects against hail damage.', None),
    (82, 'Gluttony', 'Makes the Pokémon eat any held Berry triggered by low HP below 1/2 its max HP.', None),
    (83, 'Anger Point', 'Raises Attack to the maximum of six stages upon receiving a critical hit.', None),
    (84, 'Unburden', 'Doubles Speed upon using or losing a held item.', None),
    (85, 'Heatproof', 'Halves damage from fire moves and burns.', None),
    (86, 'Simple', 'Doubles the Pokémon\'s stat modifiers.  These doubled modifiers are still capped at -6 or 6 stages.', None),
    (87, 'Dry Skin', 'Causes 1/8 max HP in damage each turn during strong sunlight, but heals for 1/8 max HP during rain.  Increases damage from fire moves to 1.25×, but absorbs water moves, healing for 1/4 max HP.', None),
    (88, 'Download', 'Raises the attack stat corresponding to the opponents\' weaker defense one stage upon entering battle.', None),
    (89, 'Iron Fist', 'Strengthens punch-based moves to 1.2× their power.', None),
    (90, 'Poison Heal', 'Heals for 1/8 max HP after each turn when poisoned in place of damage.', None),
    (91, 'Adaptability', 'Increases the same-type attack bonus from 1.5× to 2×.', None),
    (92, 'Skill Link', 'Extends two-to-five-hit moves and triple kick to their full length every time.', None),
    (93, 'Hydration', 'Cures any major status ailment after each turn during rain.', None),
    (94, 'Solar Power', 'Increases Special Attack to 1.5× but costs 1/8 max HP after each turn during strong sunlight.', None),
    (95, 'Quick Feet', 'Increases Speed to 1.5× with a major status ailment.', None),
    (96, 'Normalize', 'Makes the Pokémon\'s moves all act normal-type.', None),
    (97, 'Sniper', 'Strengthens critical hits to inflict 3× damage rather than 2×.', None),
    (98, 'Magic Guard', 'Protects against damage not directly caused by a move.', None),
    (99, 'No Guard', 'Ensures all moves used by and against the Pokémon hit.', None),
    (100, 'Stall', 'Makes the Pokémon move last within its move\'s priority bracket.', None),
    (101, 'Technician', 'Strengthens moves of 60 base power or less to 1.5× their power.', None),
    (102, 'Leaf Guard', 'Protects against major status ailments during strong sunlight.', None),
    (103, 'Klutz', 'Prevents the Pokémon from using its held item in battle.', None),
    (104, 'Mold Breaker', 'Bypasses targets\' abilities if they could hinder or prevent a move.', None),
    (105, 'Super Luck', 'Raises moves\' critical hit rates one stage.', None),
    (106, 'Aftermath', 'Damages the attacker for 1/4 its max HP when knocked out by a contact move.', None),
    (107, 'Anticipation', 'Notifies all trainers upon entering battle if an opponent has a super-effective move, self destruct, explosion, or a one-hit KO move.', None),
    (108, 'Forewarn', 'Reveals the opponents\' strongest move upon entering battle.', None),
    (109, 'Unaware', 'Ignores other Pokémon\'s stat modifiers for damage and accuracy calculation.', None),
    (110, 'Tinted Lens', 'Doubles damage inflicted with not-very-effective moves.', None),
    (111, 'Filter', 'Decreases damage taken from super-effective moves by 1/4.', None),
    (112, 'Slow Start', 'Halves Attack and Speed for five turns upon entering battle.', None),
    (113, 'Scrappy', 'Lets the Pokémon\'s normal and fighting moves hit ghost Pokémon.', None),
    (114, 'Storm Drain', 'Redirects single-target water moves to this Pokémon where possible.  Absorbs Water moves, raising Special Attack one stage.', None),
    (115, 'Ice Body', 'Heals for 1/16 max HP after each turn during hail.  Protects against hail damage.', None),
    (116, 'Solid Rock', 'Decreases damage taken from super-effective moves by 1/4.', None),
    (117, 'Snow Warning', 'Summons hail that lasts indefinitely upon entering battle.', None),
    (118, 'Honey Gather', 'The Pokémon may pick up honey after battle.', None),
    (119, 'Frisk', 'Reveals an opponent\'s held item upon entering battle.', None),
    (120, 'Reckless', 'Strengthens recoil moves to 1.2× their power.', None),
    (121, 'Multitype', 'Changes arceus\'s type and form to match its held Plate.', None),
    (122, 'Flower Gift', 'Increases friendly Pokémon\'s Attack and Special Defense to 1.5× during strong sunlight.', None),
    (123, 'Bad Dreams', 'Damages sleeping opponents for 1/8 their max HP after each turn.', None),
    (124, 'Pickpocket', 'Steals attacking Pokémon\'s held items on contact.', None),
    (125, 'Sheer Force', 'Strengthens moves with extra effects to 1.3× their power, but prevents their extra effects.', None),
    (126, 'Contrary', 'Inverts stat changes.', None),
    (127, 'Unnerve', 'Prevents opposing Pokémon from eating held Berries.', None),
    (128, 'Defiant', 'Raises Attack two stages upon having any stat lowered.', None),
    (129, 'Defeatist', 'Halves Attack and Special Attack at 50% max HP or less.', None),
    (130, 'Cursed Body', 'Has a 30% chance of Disabling any move that hits the Pokémon.', None),
    (131, 'Healer', 'Has a 30% chance of curing each adjacent ally of any major status ailment after each turn.', None),
    (132, 'Friend Guard', 'Decreases all direct damage taken by friendly Pokémon to 0.75×.', None),
    (133, 'Weak Armor', 'Raises Speed and lowers Defense by one stage each upon being hit by a physical move.', None),
    (134, 'Heavy Metal', 'Doubles the Pokémon\'s weight.', None),
    (135, 'Light Metal', 'Halves the Pokémon\'s weight.', None),
    (136, 'Multiscale', 'Halves damage taken from full HP.', None),
    (137, 'Toxic Boost', 'Increases Attack to 1.5× when poisoned.', None),
    (138, 'Flare Boost', 'Increases Special Attack to 1.5× when burned.', None),
    (139, 'Harvest', 'Has a 50% chance of restoring a used Berry after each turn if the Pokémon has held no items in the meantime.', None),
    (140, 'Telepathy', 'Protects against friendly Pokémon\'s damaging moves.', None),
    (141, 'Moody', 'Raises a random stat two stages and lowers another one stage after each turn.', None),
    (142, 'Overcoat', 'Protects against damage from weather.', None),
    (143, 'Poison Touch', 'Has a 30% chance of poisoning target Pokémon upon contact.', None),
    (144, 'Regenerator', 'Heals for 1/3 max HP upon switching out.', None),
    (145, 'Big Pecks', 'Protects against Defense drops.', None),
    (146, 'Sand Rush', 'Doubles Speed during a sandstorm.  Protects against sandstorm damage.', None),
    (147, 'Wonder Skin', 'Lowers incoming non-damaging moves\' base accuracy to exactly 50%.', None),
    (148, 'Analytic', 'Strengthens moves to 1.3× their power when moving last.', None),
    (149, 'Illusion', 'Takes the appearance of the last conscious party Pokémon upon being sent out until hit by a damaging move.', None),
    (150, 'Imposter', 'Transforms upon entering battle.', None),
    (151, 'Infiltrator', 'Bypasses light screen, reflect, and safeguard.', None),
    (152, 'Mummy', 'Changes attacking Pokémon\'s abilities to Mummy on contact.', None),
    (153, 'Moxie', 'Raises Attack one stage upon KOing a Pokémon.', None),
    (154, 'Justified', 'Raises Attack one stage upon taking damage from a dark move.', None),
    (155, 'Rattled', 'Raises Speed one stage upon being hit by a dark, ghost, or bug move.', None),
    (156, 'Magic Bounce', 'Reflects most non-damaging moves back at their user.', None),
    (157, 'Sap Sipper', 'Absorbs grass moves, raising Attack one stage.', None),
    (158, 'Prankster', 'Raises non-damaging moves\' priority by one stage.', None),
    (159, 'Sand Force', 'Strengthens rock, ground, and steel moves to 1.3× their power during a sandstorm.  Protects against sandstorm damage.', None),
    (160, 'Iron Barbs', 'Damages attacking Pokémon for 1/8 their max HP on contact.', None),
    (161, 'Zen Mode', 'Changes darmanitan\'s form after each turn depending on its HP: Zen Mode below 50% max HP, and Standard Mode otherwise.', None),
    (162, 'Victory Star', 'Increases moves\' accuracy to 1.1× for friendly Pokémon.', None),
    (163, 'Turboblaze', 'Bypasses targets\' abilities if they could hinder or prevent moves.', None),
    (164, 'Teravolt', 'Bypasses targets\' abilities if they could hinder or prevent moves.', None),
    (165, 'Aroma Veil', 'Protects allies against moves that affect their mental state.', None),
    (166, 'Flower Veil', 'Protects friendly grass Pokémon from having their stats lowered by other Pokémon.', None),
    (167, 'Cheek Pouch', 'Restores HP upon eating a Berry, in addition to the Berry\'s effect.', None),
    (168, 'Protean', 'Changes the bearer\'s type to match each move it uses.', None),
    (169, 'Fur Coat', 'Halves damage from physical attacks.', None),
    (170, 'Magician', 'Steals the target\'s held item when the bearer uses a damaging move.', None),
    (171, 'Bulletproof', 'Protects against bullet, ball, and bomb-based moves.', None),
    (172, 'Competitive', 'Raises Special Attack by two stages upon having any stat lowered.', None),
    (173, 'Strong Jaw', 'Strengthens biting moves to 1.5× their power.', None),
    (174, 'Refrigerate', 'Turns the bearer\'s normal moves into ice moves and strengthens them to 1.3× their power.', None),
    (175, 'Sweet Veil', 'Prevents friendly Pokémon from sleeping.', None),
    (176, 'Stance Change', 'Changes aegislash to Blade Forme before using a damaging move, or Shield Forme before using kings shield.', None),
    (177, 'Gale Wings', 'Raises flying moves\' priority by one stage.', None),
    (178, 'Mega Launcher', 'Strengthens aura and pulse moves to 1.5× their power.', None),
    (179, 'Grass Pelt', 'Boosts Defense while grassy terrain is in effect.', None),
    (180, 'Symbiosis', 'Passes the bearer\'s held item to an ally when the ally uses up its item.', None),
    (181, 'Tough Claws', 'Strengthens moves that make contact to 1.33× their power.', None),
    (182, 'Pixilate', 'Turns the bearer\'s normal moves into fairy moves and strengthens them to 1.3× their power.', None),
    (183, 'Gooey', 'Lowers attacking Pokémon\'s Speed by one stage on contact.', None),
    (184, 'Aerilate', 'Turns the bearer\'s normal moves into flying moves and strengthens them to 1.3× their power.', None),
    (185, 'Parental Bond', 'Lets the bearer hit twice with damaging moves.  The second hit has half power.', None),
    (186, 'Dark Aura', 'Strengthens dark moves to 1.33× their power for all friendly and opposing Pokémon.', None),
    (187, 'Fairy Aura', 'Strengthens fairy moves to 1.33× their power for all friendly and opposing Pokémon.', None),
    (188, 'Aura Break', 'Makes dark aura and fairy aura weaken moves of their respective types.', None),
    (189, 'Primordial Sea', 'Creates heavy rain, which has all the properties of Rain Dance, cannot be replaced, and causes damaging Fire moves to fail.', None),
    (190, 'Desolate Land', 'Creates extremely harsh sunlight, which has all the properties of Sunny Day, cannot be replaced, and causes damaging Water moves to fail.', None),
    (191, 'Delta Stream', 'Creates a mysterious air current, which cannot be replaced and causes moves to never be super effective against Flying Pokémon.', None),
    (202, 'Slush Rush', 'During Hail, this Pokémon has double Speed.', None),
    (256, 'Neutralizing Gas', 'Neutralizes abilities of all Pokémon in battle.', None),
    (274, 'Wind Rider', 'Gives immunity to wind moves, and causes the Pokémon\'s Attack to increase by one stage when hit by one.', None),
    (292, 'Sharpness', 'Powers up slicing moves.', None),
]
